# SharePwd.io — Burn After Reading
# Zero-knowledge secret sharing. Client-side AES-256-GCM encryption, secrets self-destruct after viewing.
# Copyright (c) 2025-2026 Antonin HILY — CTO, Jizo AI

services:
  backend:
    build:
      target: dev
    volumes:
      - ../backend:/app
    ports:
      - "8080:8080"

  frontend:
    build:
      target: dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  nginx:
    profiles:
      - disabled
